title: Tianhao's Blog
name: "Tianhao's Tech Blog"
author: Tianhao Wei
twitter_username: wei_tianhao
baseurl: ""
description: Document my learning notes.
profile_url: "http://lilianweng.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
