title: 天昊
name: "Tianhao's Blog"
author: Tianhao Wei
twitter_username: wei_tianhao
baseurl: "/blog"
description: Document my learning notes.
profile_url: "https://wei-tianhao.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
